---
- name: Pi zero setup
  hosts: localhost
  connection: local
  tasks:
    - name: Resilio sync - Add public key
      ansible.builtin.apt_key:
        url: https://linux-packages.resilio.com/resilio-sync/key.asc
        state: present
      become: yes

    - name: Resilio sync - Add repo
      ansible.builtin.apt_repository:
        repo: deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free
        state: present
      become: yes