---
- name: Pi zero setup
  hosts: localhost
  connection: local
  tasks:
    - name: Resilio sync - Add public key
      ansible.builtin.apt_key:
        url: https://linux-packages.resilio.com/resilio-sync/key.asc
        state: present
      become: yes

    - name: Resilio sync - Add repo
      ansible.builtin.apt_repository:
        repo: deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free
        state: present
      become: yes

    - name: Enable armel architecture
      command: dpkg --add-architecture armel
      become: yes

    - name: Ensure apt cache is up to date
      apt: update_cache=yes
      become: yes

    - name: Resilio sync - Install
      apt:
        name: resilio-sync:armel
        state: present
      become: yes
    
    - name: Resilio sync - Add config to set run resilio sync from the current user.
      ansible.builtin.copy:
        src: resilio-sync.service
        dest: /usr/lib/systemd/user/resilio-sync.service
        owner: root
        group: root
        mode: '0644'
      become: yes
    
    - name: Resilio sync - Start service.
      ansible.builtin.service:
        name: resilio-sync
        state: started